version: '3'

services:
  mariadb:
    container_name: mariadb
    networks: [ inception ]
    build:
      context: requeriments/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes: [ mariadb_data:/var/lib/mysql ]
    restart: unless-stopped 
    expose: [ "3306" ]

  nginx:
    container_name: nginx
    networks: [ inception ]
    build:
      context: requeriments/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes: [ wordpress:/var/www/wordpress ]
    ports: [ "443:443" ]
    restart: on-failure
    depends_on: [ wordpress ]

  wordpress:
    container_name: wordpress
    networks: [ inception ]
    build:
      context: requeriments/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes: [ wordpress:/var/www/wordpress ]
    depends_on: [ mariadb ]
    restart: on-failure
    expose: [ "9000" ]

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: "none"
      device: "/home/inception/data/mariadb"
      o: "bind"
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      device: "/home/inception/data/wordpress"
      o: "bind"

networks:
  inception:
    driver: bridge
